//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.14 at 07:06:06 PM CEST 
//


package pl.kamilszustak.labsoap.schemas.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.kamilszustak.labsoap.schemas.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.kamilszustak.labsoap.schemas.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterCallRequest }
     * 
     */
    public RegisterCallRequest createRegisterCallRequest() {
        return new RegisterCallRequest();
    }

    /**
     * Create an instance of {@link RegisterCallResponse }
     * 
     */
    public RegisterCallResponse createRegisterCallResponse() {
        return new RegisterCallResponse();
    }

    /**
     * Create an instance of {@link Exercise }
     * 
     */
    public Exercise createExercise() {
        return new Exercise();
    }

    /**
     * Create an instance of {@link ResultsRequest }
     * 
     */
    public ResultsRequest createResultsRequest() {
        return new ResultsRequest();
    }

    /**
     * Create an instance of {@link ResultsResponse }
     * 
     */
    public ResultsResponse createResultsResponse() {
        return new ResultsResponse();
    }

}
